# Generated by Django 4.2.4 on 2023-08-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='depart_num',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='oblast',
        ),
    ]
