# Generated by Django 4.2.4 on 2023-08-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellershop',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sellershop',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
