# Generated by Django 4.2.4 on 2023-08-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_sellershop_email_alter_sellershop_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellershop',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sellershop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellershop',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
