# Generated by Django 4.2.4 on 2023-08-20 00:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_sellershop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellershop',
            name='shop_image',
            field=models.ImageField(default='static/images/default/default_profile.png', upload_to=accounts.models.get_upload_path_seller_shop),
        ),
    ]
