# Generated by Django 4.2.4 on 2023-08-30 00:53

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(default=orders.models.get_tax, on_delete=django.db.models.deletion.PROTECT, to='orders.tax'),
        ),
    ]
