# Generated by Django 4.2.4 on 2023-08-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tax',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
