# Generated by Django 4.2.4 on 2023-08-29 13:18

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderstatus_default_tax_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=orders.models.get_status, on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatus'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(default=orders.models.get_tax, on_delete=django.db.models.deletion.PROTECT, to='orders.tax'),
        ),
    ]
