# Generated by Django 4.2.4 on 2023-08-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licence',
            options={'verbose_name_plural': 'Licence'},
        ),
        migrations.AlterModelOptions(
            name='main',
            options={'verbose_name_plural': 'Main'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
    ]
