# Generated by Django 4.2.4 on 2023-08-13 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlineimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
