# Generated by Django 4.2.4 on 2023-08-21 12:27

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/default/default_project.png', upload_to=store.models.get_upload_path_main_product_image),
        ),
    ]
