# Generated by Django 4.2.4 on 2023-08-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_numreviews_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numReviews',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
