# Generated by Django 4.2.4 on 2023-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_reviewrating_product_alter_reviewrating_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_old',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
